name: Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-docker:
    name: Test docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
  
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Test docker
        uses: docker/build-push-action@v2
        with:
          tags: my-portfolio:latest

      - name: Test site endpoints
        run: >-
          sudo ./install_docker.sh &&
          touch .env &&
          echo "URL=localhost:5000" >> .env &&
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env &&
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env &&
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env &&
          cat .env &&
          echo "CERTBOT_EMAIL=autumn.chiu.136@gmail.com" > nginx-certbot.env &&
          docker-compose up -d &&
          sleep 5 &&
          ./test_endpoints.sh localhost:5000
